import { CliOptions } from './types';

export const browserMockTemplate = (factories: string, options?: CliOptions) => `/**
* This file is AUTO GENERATED by msw-auto-mock, you can also commit/edit it as you prefer.
*/
/* eslint-disable */
import faker from '@faker-js/faker'

faker.seed(1);

const MAX_ARRAY_LENGTH = ${options?.maxArrayLength ?? 20};

export const factories = [${factories}];
`;
